version: "3.8"
services:
    app:
        build: ./
        restart: unless-stopped
        env_file: ./.env
        ports:
            - 4000:4000
        stdin_open: true
        tty: true
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - nitmanager_db
        links:
            - nitmanager_cache:nitmanager_cache

    nitmanager_db:
        image: postgres
        restart: always
        container_name: nitmanager_db
        ports:
            - "5431:5432"
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: adminpassword
            POSTGRES_DB: nitmanager_db
            
    nitmanager_cache:
        image: 'redis:alpine'
        container_name: nitmanager_cache
        ports:
        - '6379:6379'

networks:
  default:
    name: nithub
    external: false