version: "3.8"
services:
    app:
        build: ./
        restart: unless-stopped
        env_file: ./.env
        ports:
            - $PORT:$PORT
        stdin_open: true
        tty: true
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - db

    db:
        image: postgres
        restart: always
        env_file: ./.env
        container_name: nitprofile_database
        ports:
            - "5431:5432"
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_USER: root
            POSTGRES_PASSWORD: rootpassword
            POSTGRES_DB: nithub_management_db

networks:
  default:
    name: nithub
    external: false