version: "3.8"
services:
    app:
        build: ./
        restart: unless-stopped
        env_file: ./.env
        ports:
            - $PORT:$PORT
        stdin_open: true
        tty: true
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - db

    nit_db:
        image: postgres
        restart: always
        env_file: ./.env
        container_name: nit_db
        ports:
            - "5434:5432"
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_USER: root
            POSTGRES_PASSWORD: rootpassword
            POSTGRES_DB: nithub_management_system_db

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - "8081:8080"  # Port changed to avoid conflict

networks:
  default:
    name: nithub
    external: false